export const ROLES = {
  APPLICANT: 'applicant',
  STUDENT: 'student',
  STAFF: 'staff',
  ADMIN: 'admin',
  HOD: 'hod',
  LECTURER: 'lecturer',
  DEAN: 'dean',
  ICT: 'ict',
  STUDENT_UNION: 'student union',
  BURSARY: 'bursary',
  REGISTRY: 'registry',
  ADMISSION_OFFICER: 'admission officer',
  AUDITOR: 'auditor',
  HEALTH_CENTER: 'health center',
  WORKS: 'works',
  LIBRARY: 'library',
  PROVOST: 'provost',
};

export const HOME_BY_ROLE = {
  applicant: '/applicant/dashboard',
  student:  '/student/dashboard',
  staff:    '/staff/dashboard',
  admin:    '/staff/dashboard',

  hod: '/staff/dashboard',
  lecturer: '/staff/dashboard',
  dean: '/staff/dashboard',
  ict: '/staff/dashboard',
  'student union': '/staff/dashboard',
  bursary: '/staff/dashboard',
  registry: '/staff/dashboard',
  'admission officer': '/staff/dashboard',
  auditor: '/staff/dashboard',
  'health center': '/staff/dashboard',
  works: '/staff/dashboard',
  library: '/staff/dashboard',
  provost: '/staff/dashboard',
};
